services:
  chinwag-api:
    image: ghcr.io/perrysmithmoss/chinwag:${GIT_COMMIT_HASH:-latest}
    env_file:
      - ./server/.env.production
    environment:
      - DATABASE_URL=/run/secrets/chinwag_database_url
      - JWT_SECRET=/run/secrets/chinwag_jwt_secret
      - CLOUDINARY_CLOUD_NAME=/run/secrets/chinwag_cloudinary_cloud_name
      - CLOUDINARY_API_KEY=/run/secrets/chinwag_cloudinary_api_key
      - CLOUDINARY_API_SECRET=/run/secrets/chinwag_cloudinary_api_secret
    secrets:
      - chinwag_database_url
      - chinwag_jwt_secret
      - chinwag_cloudinary_cloud_name
      - chinwag_cloudinary_api_key
      - chinwag_cloudinary_api_secret
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.chinwag-api.loadbalancer.server.port=5500"
      - "traefik.http.routers.chinwag-api.rule=Host(`chinwag-api.perrysmithmoss.com`)"
      - "traefik.http.routers.chinwag-api.entrypoints=websecure"
      - "traefik.http.routers.chinwag-api.tls.certresolver=myresolver"
    networks:
      - portfolio_network
    deploy:
      update_config:
        order: start-first
    depends_on:
      - postgres

networks:
  portfolio_network:
    external: true

secrets:
  chinwag_database_url:
    external: true
  chinwag_jwt_secret:
    external: true
  chinwag_cloudinary_cloud_name:
    external: true
  chinwag_cloudinary_api_key:
    external: true
  chinwag_cloudinary_api_secret:
    external: true
